import type { Category, MenuItem } from "./types";

/** Monta URL do Unsplash com parâmetros de otimização. */
const img = (photoId: string) =>
  `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=900&q=70`;

export const categories: Category[] = [
  {
    id: "pizzas",
    name: "Pizzas",
    emoji: "🍕",
    description: "Massa de fermentação natural de 48h, assada em forno a lenha.",
  },
  {
    id: "lanches",
    name: "Lanches",
    emoji: "🍔",
    description: "Blend artesanal 180g na chapa, pão brioche da casa.",
  },
  {
    id: "combos",
    name: "Combos",
    emoji: "🔥",
    description: "Junta tudo e economiza — perfeito pra dividir.",
  },
  {
    id: "bebidas",
    name: "Bebidas",
    emoji: "🥤",
    description: "Geladas pra acompanhar.",
  },
  {
    id: "sobremesas",
    name: "Sobremesas",
    emoji: "🍫",
    description: "O final feliz da refeição.",
  },
];

export const menuItems: MenuItem[] = [
  // ---------- PIZZAS ----------
  {
    id: "pz-margherita",
    categoryId: "pizzas",
    name: "Margherita",
    description:
      "Molho de tomate San Marzano, muçarela de búfala, manjericão fresco e fio de azeite.",
    price: 49.9,
    image: img("photo-1574071318508-1cdbab80d002"),
    emoji: "🍕",
    tags: ["vegetariano"],
    serves: "Serve 2 pessoas · 8 fatias",
  },
  {
    id: "pz-pepperoni",
    categoryId: "pizzas",
    name: "Pepperoni",
    description: "Muçarela, pepperoni italiano fatiado na hora e orégano.",
    price: 56.9,
    image: img("photo-1513104890138-7c749659a591"),
    emoji: "🍕",
    tags: ["mais-pedido"],
    serves: "Serve 2 pessoas · 8 fatias",
  },
  {
    id: "pz-calabresa",
    categoryId: "pizzas",
    name: "Calabresa Artesanal",
    description: "Calabresa defumada, cebola roxa e azeitona preta.",
    price: 52.9,
    image: img("photo-1565299624946-b28f40a0ae38"),
    emoji: "🍕",
    serves: "Serve 2 pessoas · 8 fatias",
  },
  {
    id: "pz-4queijos",
    categoryId: "pizzas",
    name: "Quatro Queijos",
    description: "Muçarela, gorgonzola, parmesão e catupiry cremoso.",
    price: 58.9,
    image: img("photo-1548369937-47519962c11a"),
    emoji: "🧀",
    tags: ["vegetariano"],
    serves: "Serve 2 pessoas · 8 fatias",
  },
  {
    id: "pz-portuguesa",
    categoryId: "pizzas",
    name: "Portuguesa",
    description: "Presunto, ovo, cebola, ervilha, muçarela e azeitona.",
    price: 54.9,
    image: img("photo-1571407970349-bc81e7e96d47"),
    emoji: "🍕",
    serves: "Serve 2 pessoas · 8 fatias",
  },
  {
    id: "pz-frango-catupiry",
    categoryId: "pizzas",
    name: "Frango com Catupiry",
    description: "Frango desfiado temperado e catupiry original.",
    price: 55.9,
    image: img("photo-1594007654729-407eedc4be65"),
    emoji: "🍗",
    tags: ["mais-pedido"],
    serves: "Serve 2 pessoas · 8 fatias",
  },
  {
    id: "pz-diavola",
    categoryId: "pizzas",
    name: "Diavola",
    description: "Muçarela, salame picante, pimenta calabresa e um toque de mel.",
    price: 59.9,
    image: img("photo-1604382354936-07c5d9983bd3"),
    emoji: "🌶️",
    tags: ["novo", "picante"],
    serves: "Serve 2 pessoas · 8 fatias",
  },
  {
    id: "pz-vegetariana",
    categoryId: "pizzas",
    name: "Vegetariana da Casa",
    description: "Abobrinha, berinjela, pimentão, tomate seco e rúcula.",
    price: 53.9,
    image: img("photo-1590534247854-e97d5e3feef6"),
    emoji: "🥗",
    tags: ["vegetariano"],
    serves: "Serve 2 pessoas · 8 fatias",
  },

  // ---------- LANCHES ----------
  {
    id: "ln-cheeseburger",
    categoryId: "lanches",
    name: "Cheeseburger Clássico",
    description:
      "Blend 180g, cheddar, picles, cebola e molho da casa no pão brioche.",
    price: 32.9,
    image: img("photo-1568901346375-23c9450c58cd"),
    emoji: "🍔",
    tags: ["mais-pedido"],
  },
  {
    id: "ln-bacon-duplo",
    categoryId: "lanches",
    name: "Bacon Duplo",
    description:
      "Dois blends 180g, cheddar duplo, bacon crocante e maionese defumada.",
    price: 44.9,
    image: img("photo-1553979459-d2229ba7433b"),
    emoji: "🥓",
  },
  {
    id: "ln-smash-salada",
    categoryId: "lanches",
    name: "Smash Salada",
    description: "Dois smash 90g, alface, tomate, cebola e maionese verde.",
    price: 34.9,
    image: img("photo-1550547660-d9450f859349"),
    emoji: "🍔",
  },
  {
    id: "ln-frango-crispy",
    categoryId: "lanches",
    name: "Frango Crispy",
    description:
      "Peito de frango empanado, coleslaw, picles e molho honey mustard.",
    price: 33.9,
    image: img("photo-1606755962773-d324e0a13086"),
    emoji: "🍗",
    tags: ["novo"],
  },
  {
    id: "ln-veggie",
    categoryId: "lanches",
    name: "Veggie Portobello",
    description: "Cogumelo portobello grelhado, queijo, rúcula e tomate confit.",
    price: 31.9,
    image: img("photo-1520072959219-c595dc870360"),
    emoji: "🍄",
    tags: ["vegetariano"],
  },
  {
    id: "ln-costela-bbq",
    categoryId: "lanches",
    name: "Costela BBQ",
    description:
      "Costela desfiada 10h, onion rings, cheddar e molho barbecue picante.",
    price: 46.9,
    image: img("photo-1594212699903-ec8a3eca50f5"),
    emoji: "🍖",
    tags: ["picante"],
  },

  // ---------- COMBOS ----------
  {
    id: "cb-solo",
    categoryId: "combos",
    name: "Combo Solo",
    description: "1 Cheeseburger Clássico + batata rústica + refri lata 350ml.",
    price: 44.9,
    image: img("photo-1571091718767-18b5b1457add"),
    emoji: "🍟",
  },
  {
    id: "cb-dupla",
    categoryId: "combos",
    name: "Combo Dupla",
    description: "2 lanches à escolha + batata grande + 2 refris lata.",
    price: 82.9,
    image: img("photo-1610614819513-58e34989848b"),
    emoji: "🔥",
    tags: ["mais-pedido"],
  },
  {
    id: "cb-noite-pizza",
    categoryId: "combos",
    name: "Noite da Pizza",
    description: "1 pizza grande + borda recheada de catupiry + refri 2L.",
    price: 74.9,
    image: img("photo-1593560708920-61dd98c46a4e"),
    emoji: "🍕",
  },

  // ---------- BEBIDAS ----------
  {
    id: "bb-refri-lata",
    categoryId: "bebidas",
    name: "Refrigerante Lata 350ml",
    description: "Coca-Cola, Guaraná Antarctica, Fanta Laranja ou Sprite.",
    price: 7.0,
    image: img("photo-1554866585-cd94860890b7"),
    emoji: "🥤",
  },
  {
    id: "bb-coca-2l",
    categoryId: "bebidas",
    name: "Coca-Cola 2L",
    description: "Garrafa gelada pra dividir.",
    price: 14.0,
    image: img("photo-1622483767028-3f66f32aef97"),
    emoji: "🥤",
  },
  {
    id: "bb-suco",
    categoryId: "bebidas",
    name: "Suco Natural 500ml",
    description: "Laranja, maracujá, limão ou abacaxi com hortelã.",
    price: 12.9,
    image: img("photo-1600271886742-f049cd451bba"),
    emoji: "🍹",
  },
  {
    id: "bb-limonada",
    categoryId: "bebidas",
    name: "Limonada Suíça",
    description: "Feita na hora, bem gelada.",
    price: 11.9,
    image: img("photo-1621263764928-df1444c5e859"),
    emoji: "🍋",
  },
  {
    id: "bb-cerveja",
    categoryId: "bebidas",
    name: "Cerveja Long Neck",
    description: "Heineken, Original ou Corona.",
    price: 12.0,
    image: img("photo-1608270586620-248524c67de9"),
    emoji: "🍺",
  },
  {
    id: "bb-agua",
    categoryId: "bebidas",
    name: "Água Mineral 500ml",
    description: "Com ou sem gás.",
    price: 5.0,
    image: img("photo-1523362628745-0c100150b504"),
    emoji: "💧",
  },

  // ---------- SOBREMESAS ----------
  {
    id: "sb-petit-gateau",
    categoryId: "sobremesas",
    name: "Petit Gâteau",
    description: "Bolo quente de chocolate com recheio cremoso e sorvete de creme.",
    price: 24.9,
    image: img("photo-1624353365286-3f8d62daad51"),
    emoji: "🍫",
    tags: ["mais-pedido"],
  },
  {
    id: "sb-brownie",
    categoryId: "sobremesas",
    name: "Brownie da Casa",
    description: "Brownie com nozes, calda quente de chocolate e sorvete.",
    price: 22.9,
    image: img("photo-1606313564200-e75d5e30476c"),
    emoji: "🍰",
  },
  {
    id: "sb-cheesecake",
    categoryId: "sobremesas",
    name: "Cheesecake de Frutas Vermelhas",
    description: "Base crocante, creme suave e calda artesanal de frutas vermelhas.",
    price: 21.9,
    image: img("photo-1533134242443-d4fd215305ad"),
    emoji: "🍓",
    tags: ["novo"],
  },
  {
    id: "sb-pizza-nutella",
    categoryId: "sobremesas",
    name: "Pizza Doce de Nutella",
    description: "Muçarela fina, Nutella, morango fatiado e leite ninho.",
    price: 42.9,
    image: "", // usa placeholder da marca (emoji) — sem foto boa o suficiente no acervo

    emoji: "🍫",
    tags: ["vegetariano"],
  },
];

export const itemsByCategory = (categoryId: string): MenuItem[] =>
  menuItems.filter((item) => item.categoryId === categoryId);
